package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hegner123/nostop/pkg/nostop"
)

// toolAccessLevel describes what tools Claude can use.
type toolAccessLevel int

const (
	toolAccessNone     toolAccessLevel = iota // Chat only, no tools
	toolAccessReadOnly                        // Read + search tools only
	toolAccessStandard                        // Read + write + search + analysis (no delete, no bash)
	toolAccessFull                            // All tools including bash and delete
)

// firstRunSetup runs the interactive first-run configuration wizard.
// Returns the path the config was written to, or an error.
func firstRunSetup() (string, error) {
	scanner := bufio.NewScanner(os.Stdin)

	fmt.Println("Welcome to Nostop!")
	fmt.Println("No configuration file found. Let's set one up.")
	fmt.Println()

	// --- API Key ---
	apiKey := os.Getenv(envAPIKey)
	if apiKey != "" {
		fmt.Printf("API key detected from %s environment variable.\n\n", envAPIKey)
	} else {
		fmt.Println("An Anthropic API key is required.")
		fmt.Printf("You can also set this later via the %s environment variable.\n", envAPIKey)
		fmt.Print("API key (leave empty to skip): ")
		scanner.Scan()
		apiKey = strings.TrimSpace(scanner.Text())
		fmt.Println()
	}

	// --- Tool Access Level ---
	fmt.Println("Tool access levels control what Claude can do during conversations:")
	fmt.Println()
	fmt.Println("  1) Chat only     - No tool access. Claude responds with text only.")
	fmt.Println("  2) Read-only     - Claude can read files and search code, but cannot")
	fmt.Println("                     modify anything.")
	fmt.Println("  3) Standard      - Claude can read, write, and search files. No shell")
	fmt.Println("                     access or file deletion. (recommended)")
	fmt.Println("  4) Full access   - Claude can read, write, delete files and run shell")
	fmt.Println("                     commands. Use in trusted environments only.")
	fmt.Println()
	fmt.Print("Choose access level [1-4] (default: 3): ")
	scanner.Scan()
	choice := strings.TrimSpace(scanner.Text())

	level := toolAccessStandard
	switch choice {
	case "1":
		level = toolAccessNone
	case "2":
		level = toolAccessReadOnly
	case "3", "":
		level = toolAccessStandard
	case "4":
		level = toolAccessFull
	default:
		fmt.Printf("Unknown choice %q, using standard.\n", choice)
		level = toolAccessStandard
	}
	fmt.Println()

	// --- Build config ---
	cfg := nostop.DefaultFileConfig()

	if apiKey != "" {
		cfg.API.Key = apiKey
	}

	applyToolAccess(&cfg, level)

	// --- Write config ---
	configPath := nostop.GetConfigPath()
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create config directory: %w", err)
	}

	content := buildConfigContent(&cfg, level, apiKey)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write config: %w", err)
	}

	// --- Summary ---
	fmt.Printf("Configuration written to: %s\n", configPath)
	fmt.Println()
	printAccessSummary(level)
	fmt.Println()
	fmt.Println("You can change these settings anytime by editing the config file.")
	fmt.Println("Starting Nostop...")
	fmt.Println()

	return configPath, nil
}

// applyToolAccess configures the ToolsConfig based on the chosen access level.
func applyToolAccess(cfg *nostop.FileConfig, level toolAccessLevel) {
	switch level {
	case toolAccessNone:
		cfg.Tools.Enabled = false

	case toolAccessReadOnly:
		cfg.Tools.Enabled = true
		cfg.Tools.DisabledTools = []string{
			"write", "bash", "delete", "repfor", "notab", "splice", "split", "utf8",
		}

	case toolAccessStandard:
		cfg.Tools.Enabled = true
		cfg.Tools.DisabledTools = []string{
			"bash", "delete",
		}

	case toolAccessFull:
		cfg.Tools.Enabled = true
		cfg.Tools.DisabledTools = nil
	}
}

// buildConfigContent generates the TOML config file content with comments.
func buildConfigContent(cfg *nostop.FileConfig, level toolAccessLevel, apiKey string) string {
	var b strings.Builder

	b.WriteString("# Nostop Configuration File\n")
	b.WriteString("# https://github.com/hegner123/nostop\n")
	b.WriteString("# Generated by first-run setup\n\n")

	b.WriteString("[api]\n")
	if apiKey != "" {
		fmt.Fprintf(&b, "key = %q\n", apiKey)
	} else {
		b.WriteString("# API key for Anthropic Claude API\n")
		b.WriteString("# Set via ANTHROPIC_API_KEY environment variable or uncomment below:\n")
		b.WriteString("# key = \"sk-ant-...\"\n")
	}
	fmt.Fprintf(&b, "timeout = %d\n\n", cfg.API.Timeout)

	b.WriteString("[context]\n")
	fmt.Fprintf(&b, "max_tokens = %d\n", cfg.Context.MaxTokens)
	fmt.Fprintf(&b, "archive_threshold = %.2f\n", cfg.Context.ArchiveThreshold)
	fmt.Fprintf(&b, "archive_target = %.2f\n\n", cfg.Context.ArchiveTarget)

	b.WriteString("[models]\n")
	fmt.Fprintf(&b, "chat = %q\n", cfg.Models.Chat)
	fmt.Fprintf(&b, "detection = %q\n\n", cfg.Models.Detection)

	b.WriteString("[database]\n")
	fmt.Fprintf(&b, "path = %q\n\n", cfg.Database.Path)

	b.WriteString("[ui]\n")
	fmt.Fprintf(&b, "theme = %q\n", cfg.UI.Theme)
	fmt.Fprintf(&b, "auto_refresh = %v\n\n", cfg.UI.AutoRefresh)

	b.WriteString("[tools]\n")
	switch level {
	case toolAccessNone:
		b.WriteString("# Tool access: chat only (no tools)\n")
		b.WriteString("enabled = false\n")
	case toolAccessReadOnly:
		b.WriteString("# Tool access: read-only (search and read, no modifications)\n")
		b.WriteString("enabled = true\n")
		b.WriteString("disabled_tools = [\"write\", \"bash\", \"delete\", \"repfor\", \"notab\", \"splice\", \"split\", \"utf8\"]\n")
	case toolAccessStandard:
		b.WriteString("# Tool access: standard (read, write, search — no shell or delete)\n")
		b.WriteString("enabled = true\n")
		b.WriteString("disabled_tools = [\"bash\", \"delete\"]\n")
	case toolAccessFull:
		b.WriteString("# Tool access: full (all tools including shell and delete)\n")
		b.WriteString("enabled = true\n")
	}
	fmt.Fprintf(&b, "timeout = %d\n", 30)

	return b.String()
}

// printAccessSummary prints a human-readable summary of the chosen access level.
func printAccessSummary(level toolAccessLevel) {
	switch level {
	case toolAccessNone:
		fmt.Println("Access level: Chat only")
		fmt.Println("  Claude will respond with text only — no tool access.")

	case toolAccessReadOnly:
		fmt.Println("Access level: Read-only")
		fmt.Println("  Claude can: read files, search code, view directory trees")
		fmt.Println("  Claude cannot: write files, run commands, delete anything")

	case toolAccessStandard:
		fmt.Println("Access level: Standard")
		fmt.Println("  Claude can: read files, write files, search, analyze code")
		fmt.Println("  Claude cannot: run shell commands, delete files")

	case toolAccessFull:
		fmt.Println("Access level: Full")
		fmt.Println("  Claude can: read, write, delete files, run shell commands")
		fmt.Println("  Use with caution in trusted environments only.")
	}
}
